### ISSUE TITLE
Add support for WebSocket clients

### ISSUE THREAD

**Issue by fmvilas** [asyncapi/glee#259]
#### Reason/Context

Currently, Glee only supports creating a WebSocket server. That makes it unusable when someone wants to build a WebSocket client to connect to an existing WS server.

#### Description

We already have support for WebSocket but it's always assuming we want to create a server, and that's plain wrong. Instead, Glee should default to creating a WS client and only create a server when we mark the `server` definition in the AsyncAPI file as "local".

For instance:

```yaml
asyncapi: 2.3.0
servers:
  myWebsiteWebSocketServer:
    url: 'ws://mywebsite.com/ws'
    protocol: ws
    x-kind: local
  someProductWSServer:
    url: 'ws://someproduct.com/ws'
    protocol: ws
```

The server `myWebsiteWebSocketServer` is a WS server we want to create with Glee but the server `someProductWSServer` is a remote server we want to send/receive information to/from. The former is what's already implemented and the latter is what we should be implementing as part of this issue. Notice the `x-kind: local` on the `myWebsiteWebSocketServer` server. Only when this is found, we should create a server, otherwise, we should default to a client. Another allowed value for `x-kind` is `remote`.

#### Notes

`x-kind` is an extension we're creating as part of this issue, this is not defined anywhere yet so we have some freedom defining how we want it to be. I'm trying to make it as similar as possible to the [Remotes and local servers issue on the spec](https://github.com/asyncapi/spec/issues/689). In v3, we may end up having two root keys: `servers` (local servers) and `remotes` (remote servers or brokers). For v2.x (the current version), I think it's just fine if we add the `x-kind` extension but I'm happy to listen for alternatives.
