### ISSUE TITLE
support parameters for channel address.

### ISSUE THREAD

**Issue by KhudaDad414** [asyncapi/glee#555]
#### Problem

With the introduction of [parameters for channel](https://www.asyncapi.com/docs/reference/specification/v3.0.0-next-major-spec.14#channelObject) addresses in AsyncAPI spec v3, users have the flexibility to define dynamic parts in the channel address. This feature is currently not supported in Glee, meaning Glee can't utilize or understand these parameterized channels.

---

#### Solution

Introduce support for parsing and utilizing channel address parameters in Glee. When a channel is defined with parameters like:

```yaml
channels:
  mychannel:
    address: /{userId}/details
    parameters:
      userId:
        description: Id of the user.
        location: $message.payload#/userId
        default: 6f0ca58d-95ac-4817-9e39-9258f5cc75bd
```

Glee should be able to interpret this and correctly map messages to this dynamically constructed channel address.

#### Rabbit Holes
 parameters mean different things for `send` and `receive` operations and not sure how this feature affects different protocols.

---

#### Scope

- [ ] support parameters in http client and server.
- [ ] support parameters in websockets client and server.
- [ ] support parameters in socket.io
- [ ] support parameters in kafka.
- [ ] support parameters in mqtt.

---

#### Out of Bounds

- any other improvements and features of spec 3 are outside of the scope.

---

#### Success Criteria

1. Glee should be able to correctly route messages to parameterized channel addresses.
2. Existing functionality should not be broken; it should be backward compatible.
3. Unit tests should cover the new features and pass successfully.

By meeting these criteria, we can consider the solution a success.
